// 10
//const test = { "response_code": 0, "results": [{ "type": "multiple", "difficulty": "medium", "category": "Celebrities", "question": "Which TV chef wrote an autobiography titled &quot;Humble Pie&quot;?", "correct_answer": "Gordon Ramsay", "incorrect_answers": ["Jamie Oliver", "Ainsley Harriott", "Antony Worrall Thompson"] }, { "type": "multiple", "difficulty": "medium", "category": "History", "question": "During what war did the &quot;Cuban Missile Crisis&quot; occur?", "correct_answer": "Cold War", "incorrect_answers": ["World War I", "World War II", "Revolutionary War"] }, { "type": "multiple", "difficulty": "medium", "category": "Mythology", "question": "Who is the god of war in Polynesian mythology?", "correct_answer": "&#039;Oro", "incorrect_answers": ["Hina", "Kohara", "M\u0101ui"] }, { "type": "multiple", "difficulty": "hard", "category": "Mythology", "question": "Talos, the mythical giant bronze man, was the protector of which island?", "correct_answer": "Crete", "incorrect_answers": ["Sardinia", "Sicily", "Cyprus"] }, { "type": "multiple", "difficulty": "easy", "category": "Science: Gadgets", "question": "Which of the following is not a type of computer mouse?", "correct_answer": "Smoothie mouse", "incorrect_answers": ["Drum mouse", "Trackball mouse", "Optical mouse"] }, { "type": "multiple", "difficulty": "medium", "category": "History", "question": "Which Las Vegas casino was originally constructed and operated by mobster Bugsy Siegel?", "correct_answer": "The Flamingo", "incorrect_answers": ["The MGM Grand", "The Sands", "The Sahara"] }, { "type": "multiple", "difficulty": "hard", "category": "Geography", "question": "What year is on the flag of the US state Wisconsin?", "correct_answer": "1848", "incorrect_answers": ["1634", "1783", "1901"] }, { "type": "multiple", "difficulty": "easy", "category": "Entertainment: Video Games", "question": "How do you tame a horse in Minecraft?", "correct_answer": "By continually mounting it", "incorrect_answers": ["By feeding it Wheat", "By feeding it Sugar", "By petting it"] }, { "type": "multiple", "difficulty": "medium", "category": "Entertainment: Japanese Anime &amp; Manga", "question": "In &quot;To Love-Ru&quot;, who is the first to hear of Yami&#039;s past from her?", "correct_answer": "Rito", "incorrect_answers": ["Mikan", "Lala", "Haruna"] }, { "type": "multiple", "difficulty": "medium", "category": "History", "question": "When was &quot;The Gadget&quot;, the first nuclear device to be detonated, tested?", "correct_answer": "July 16, 1945", "incorrect_answers": ["June 22, 1945", "August 6, 1945", "April 5, 1945"] }] };

// 2
const test = { "response_code": 0, "results": [{ "type": "multiple", "difficulty": "medium", "category": "History", "question": "During what war did the &quot;Cuban Missile Crisis&quot; occur?", "correct_answer": "Cold War", "incorrect_answers": ["World War I", "World War II", "Revolutionary War"] }, { "type": "multiple", "difficulty": "medium", "category": "Celebrities", "question": "Which TV chef wrote an autobiography titled &quot;Humble Pie&quot;?", "correct_answer": "Gordon Ramsay", "incorrect_answers": ["Jamie Oliver", "Ainsley Harriott", "Antony Worrall Thompson"] }] };

// 1
//const test = { "response_code": 0, "results": [{ "type": "multiple", "difficulty": "easy", "category": "Entertainment: Video Games", "question": "How do you tame a horse in Minecraft?", "correct_answer": "By continually it mounting it, I do think yes absolutely yes", "incorrect_answers": ["By feeding it Wheat", "By feeding it Sugar", "By petting it"] }] };



export  default test ;